#server:
#  port: 8443
#  ssl:
#    key-store: /etc/letsencrypt/live/chatskhu.duckdns.org/keystore.p12
#    key-store-password: ${KEY_STORE_PASSWORD}
#    key-store-type: pkcs12
#    key-alias: tomcat
#    enabled: true

spring:
  profiles:
    active: local
    group:
      local: common
      prod: common

---
spring:
  config:
    activate:
      on-profile: common

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true

oauth:
  kakao:
    rest-api-key: ${KAKAO_REST_API_KEY}
    redirect-url: ${KAKAO_REDIRECT_URL}
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-url: ${GOOGLE_REDIRECT_URL}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
 
openai: # common 프로파일에 openai설정 추가
  model: gpt-3.5-turbo
  gpt-api-key: ${OPENAI_API_KEY}

jwt:
  secret: ${JWT_SECRET}

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: ${DB_URL}?rewriteBatchedStatements=true&profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLog=999999
  jpa:
    show-sql: true
    
openai: # local 프로파일에 openai설정 추가
  model: gpt-4
  gpt-api-key: ${OPENAI_API_KEY}

---
spring:
  config:
    activate:
      on-profile: prod

  jpa:
    show-sql: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true

